version: "2"
volumes:
  postgresqldata:
services:
  postgres:
    container_name: postgres
    image: postgres:latest
    environment:
      POSTGRES_USER: docker_user
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: projectdb
    ports:
      - "5432:5432"
    volumes:
      - postgresqldata:/var/lib/postgresql/data

  go:
    build: ./